import React, { useEffect, useState } from 'react';
import { Languages } from 'lucide-react';
import { exportCAP, fetchCAPCentre } from '../services/api';
export const CAPCentrePage: React.FC = () => {
  const [data, setData] = useState<any>(); const [id, setId] = useState(''); const [error, setError] = useState('');
  const load = () => fetchCAPCentre().then(setData).catch(e => setError(e.message));
  useEffect(() => { void load(); }, []);
  return <div className="space-y-4 p-4 lg:p-6"><header><h1 className="flex items-center gap-2 text-xl font-semibold"><Languages className="h-5 w-5" />CAP 1.2 Warning Centre</h1><p className="text-xs text-text-muted">CAP-compatible interoperability exports; no official NDMA/SACHET connection is claimed.</p></header>{error && <div role="alert" className="text-red-200">{error}</div>}<section className="rounded-lg border border-border-subtle bg-bg-secondary p-4"><div className="grid gap-2 sm:grid-cols-4">{data?.status.channels.map((x: any) => <div key={x.channel} className="rounded bg-bg-surface p-3 text-xs"><strong>{x.channel}</strong><div className="mt-1 text-amber-200">{x.state}</div></div>)}</div><div className="mt-4 flex gap-2"><input aria-label="Alert ID" value={id} onChange={e => setId(e.target.value)} placeholder="Existing alert ID" className="flex-1 rounded bg-bg-surface px-3 py-2 text-xs" /><button disabled={!id} onClick={() => exportCAP(id).then(() => { setId(''); void load(); }).catch(e => setError(e.message))} className="rounded bg-accent-info px-3 py-2 text-xs text-bg-primary disabled:opacity-40">Create bilingual export</button></div></section><section><h2 className="mb-2 text-sm font-semibold">Validated exports</h2>{!data?.exports.length ? <div className="rounded border border-border-subtle p-4 text-xs text-text-muted">No CAP exports generated.</div> : data.exports.map((x: any) => <article key={x.id} className="mb-2 rounded border border-border-subtle bg-bg-secondary p-3 text-xs"><strong>{x.alert_id}</strong> · {x.lifecycle} · {x.validation_state}<div className="text-text-muted">{x.languages.join(', ')} · {x.provenance}</div></article>)}</section><section><h2 className="mb-2 text-sm font-semibold">Delivery proof</h2><p className="text-xs text-text-muted">A delivery is proven only by a persisted provider receipt. No provider is configured.</p></section></div>;
};
